Notebook prirejen s strani http://www.pieriandata.com

# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

We will only learn the basics of NumPy. To get started we need to install it!

## Import

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Create NumPy Array manualy

In [3]:
my_list = [1,2,3]
print(my_list)
print(type(my_list))

my_numpy_list = np.array(my_list)
print(my_numpy_list)
print(type(my_numpy_list))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# navaden list lahko množiš samo preko dostopanja do vsakega elementa posebej
print(my_list * 4)
print([x*4 for x in my_list])

# na numpy seznamu pa lahko izvajaš operacije direktno
print(my_numpy_list * 4)
print(my_numpy_list ** 2)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[4, 8, 12]
[ 4  8 12]
[1 4 9]


In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
print(type(my_matrix))

my_matrix = np.array(my_matrix)
print(my_matrix)
print(type(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## Create Create NumPy Array with Built-in Methods
There are lots of built-in ways to generate arrays.

### arange

- Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]
- np.arange( START, STOP, STEP )

In [11]:
# np.arange(START, STOP, STEP)
print(np.arange(10))
print(np.arange(0,10,0.5))

print(np.arange(1, 10))
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones(1)

array([1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
- Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]
- ODLIČNO ZA GENERIRANJE GRAFOV, ker so razdelki enakomerno porazdeljeni

In [27]:
print(np.arange(0,10.1,0.1))
print(np.linspace(0,10,10))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [28]:
# naloga naredi enakomerne točke, z razdelkom po 1 med 0 in 10, vključno z 0 in 10
# 0<= x <= 10
# trik v razmišljnju, to zajema 11 točk

np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [29]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [30]:
np.random.rand(10)

array([0.77843579, 0.8297702 , 0.33246318, 0.0900703 , 0.94621103,
       0.80713413, 0.55516857, 0.45374577, 0.42368316, 0.70114063])

In [32]:
np.random.rand(2,2)

array([[0.72653919, 0.81337994],
       [0.37840906, 0.77767253]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [33]:
np.random.randn(2)

array([0.96073771, 0.23567349])

In [34]:
np.random.randn(2,2)

array([[-0.22245864,  1.22875328],
       [ 0.10723212,  0.59561422]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [41]:
np.random.randint(1,6)

5

In [42]:
np.random.randint(1, 100, 10)

array([85, 67, 45, 39, 72, 61, 28, 14, 79, 69])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
np.random.rand(5)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615, 0.60111501])

In [ ]:
np.random.seed(42)
np.random.rand(4)

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [48]:
arr = np.arange(16)
ranarr = np.random.randint(0,50,10)

print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[23  2 21  1 23 43 29 37  1 20]


## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [49]:
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
print(ranarr.max())
print(ranarr.min())
print(ranarr.mean())

43
1
20.0


## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [51]:
# Vector
arr.shape

(16,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(5,5)

In [ ]:
arr.reshape(5,5).shape

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [ ]:
arr.dtype

In [ ]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

# Great Job!